export const BODY_STYLES = {
  accentColor: 'rgb(94, 158, 255)',
  additiveSymbols: '',
  alignContent: 'normal',
  alignItems: 'normal',
  alignSelf: 'auto',
  alignmentBaseline: 'auto',
  all: '',
  animation: 'none 0s ease 0s 1 normal none running',
  animationComposition: 'replace',
  animationDelay: '0s',
  animationDirection: 'normal',
  animationDuration: '0s',
  animationFillMode: 'none',
  animationIterationCount: '1',
  animationName: 'none',
  animationPlayState: 'running',
  animationTimingFunction: 'ease',
  appRegion: 'none',
  appearance: 'none',
  ascentOverride: '',
  aspectRatio: 'auto',
  backdropFilter: 'none',
  backfaceVisibility: 'visible',
  background:
    'rgba(0, 0, 0, 0) none repeat scroll 0% 0% / auto padding-box border-box',
  backgroundAttachment: 'scroll',
  backgroundBlendMode: 'normal',
  backgroundClip: 'border-box',
  backgroundColor: 'rgba(0, 0, 0, 0)',
  backgroundImage: 'none',
  backgroundOrigin: 'padding-box',
  backgroundPosition: '0% 0%',
  backgroundPositionX: '0%',
  backgroundPositionY: '0%',
  backgroundRepeat: 'repeat',
  backgroundRepeatX: 'repeat',
  backgroundRepeatY: 'repeat',
  backgroundSize: 'auto',
  basePalette: '',
  baselineShift: '0',
  baselineSource: 'auto',
  blockSize: '8066.71',
  border: '0 none rgb(255, 255, 255)',
  borderBlock: '0 none rgb(255, 255, 255)',
  borderBlockColor: 'rgb(255, 255, 255)',
  borderBlockEnd: '0 none rgb(255, 255, 255)',
  borderBlockEndColor: 'rgb(255, 255, 255)',
  borderBlockEndStyle: 'none',
  borderBlockEndWidth: '0',
  borderBlockStart: '0 none rgb(255, 255, 255)',
  borderBlockStartColor: 'rgb(255, 255, 255)',
  borderBlockStartStyle: 'none',
  borderBlockStartWidth: '0',
  borderBlockStyle: 'none',
  borderBlockWidth: '0',
  borderBottom: '0 none rgb(255, 255, 255)',
  borderBottomColor: 'rgb(255, 255, 255)',
  borderBottomLeftRadius: '0',
  borderBottomRightRadius: '0',
  borderBottomStyle: 'none',
  borderBottomWidth: '0',
  borderCollapse: 'separate',
  borderColor: 'rgb(255, 255, 255)',
  borderEndEndRadius: '0',
  borderEndStartRadius: '0',
  borderImage: 'none',
  borderImageOutset: '0',
  borderImageRepeat: 'stretch',
  borderImageSlice: '100%',
  borderImageSource: 'none',
  borderImageWidth: '1',
  borderInline: '0 none rgb(255, 255, 255)',
  borderInlineColor: 'rgb(255, 255, 255)',
  borderInlineEnd: '0 none rgb(255, 255, 255)',
  borderInlineEndColor: 'rgb(255, 255, 255)',
  borderInlineEndStyle: 'none',
  borderInlineEndWidth: '0',
  borderInlineStart: '0 none rgb(255, 255, 255)',
  borderInlineStartColor: 'rgb(255, 255, 255)',
  borderInlineStartStyle: 'none',
  borderInlineStartWidth: '0',
  borderInlineStyle: 'none',
  borderInlineWidth: '0',
  borderLeft: '0 none rgb(255, 255, 255)',
  borderLeftColor: 'rgb(255, 255, 255)',
  borderLeftStyle: 'none',
  borderLeftWidth: '0',
  borderRadius: '0',
  borderRight: '0 none rgb(255, 255, 255)',
  borderRightColor: 'rgb(255, 255, 255)',
  borderRightStyle: 'none',
  borderRightWidth: '0',
  borderSpacing: '0 0',
  borderStartEndRadius: '0',
  borderStartStartRadius: '0',
  borderStyle: 'none',
  borderTop: '0 none rgb(255, 255, 255)',
  borderTopColor: 'rgb(255, 255, 255)',
  borderTopLeftRadius: '0',
  borderTopRightRadius: '0',
  borderTopStyle: 'none',
  borderTopWidth: '0',
  borderWidth: '0',
  bottom: 'auto',
  boxShadow: 'none',
  boxSizing: 'content-box',
  breakAfter: 'auto',
  breakBefore: 'auto',
  breakInside: 'auto',
  bufferedRendering: 'auto',
  captionSide: 'top',
  caretColor: 'rgb(255, 255, 255)',
  clear: 'none',
  clip: 'auto',
  clipPath: 'none',
  clipRule: 'nonzero',
  color: 'rgb(0, 0, 0)',
  colorInterpolation: 'srgb',
  colorInterpolationFilters: 'linearrgb',
  colorRendering: 'auto',
  colorScheme: 'dark',
  columnCount: 'auto',
  columnFill: 'balance',
  columnGap: 'normal',
  columnRule: '0 none rgb(255, 255, 255)',
  columnRuleColor: 'rgb(255, 255, 255)',
  columnRuleStyle: 'none',
  columnRuleWidth: '0',
  columnSpan: 'none',
  columnWidth: 'auto',
  columns: 'auto auto',
  contain: 'none',
  containIntrinsicBlockSize: 'none',
  containIntrinsicHeight: 'none',
  containIntrinsicInlineSize: 'none',
  containIntrinsicSize: 'none',
  containIntrinsicWidth: 'none',
  container: 'none',
  containerName: 'none',
  containerType: 'normal',
  content: 'normal',
  contentVisibility: 'visible',
  counterIncrement: 'none',
  counterReset: 'none',
  counterSet: 'none',
  cursor: 'auto',
  cx: '0',
  cy: '0',
  d: 'none',
  descentOverride: '',
  direction: 'ltr',
  display: 'block',
  dominantBaseline: 'auto',
  emptyCells: 'show',
  fallback: '',
  fill: 'rgb(0, 0, 0)',
  fillOpacity: '1',
  fillRule: 'nonzero',
  filter: 'none',
  flex: '0 1 auto',
  flexBasis: 'auto',
  flexDirection: 'row',
  flexFlow: 'row nowrap',
  flexGrow: '0',
  flexShrink: '1',
  flexWrap: 'nowrap',
  float: 'none',
  floodColor: 'rgb(0, 0, 0)',
  floodOpacity: '1',
  font: '20 / 35 Inter, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
  fontDisplay: '',
  fontFamily:
    'Inter, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
  fontFeatureSettings: 'normal',
  fontKerning: 'auto',
  fontOpticalSizing: 'auto',
  fontPalette: 'normal',
  fontSize: '20',
  fontStretch: '100%',
  fontStyle: 'normal',
  fontSynthesis: 'weight style small-caps',
  fontSynthesisSmallCaps: 'auto',
  fontSynthesisStyle: 'auto',
  fontSynthesisWeight: 'auto',
  fontVariant: 'normal',
  fontVariantAlternates: 'normal',
  fontVariantCaps: 'normal',
  fontVariantEastAsian: 'normal',
  fontVariantLigatures: 'normal',
  fontVariantNumeric: 'normal',
  fontVariationSettings: 'normal',
  fontWeight: '400',
  forcedColorAdjust: 'auto',
  gap: 'normal',
  grid: 'none / none / none / row / auto / auto',
  gridArea: 'auto / auto / auto / auto',
  gridAutoColumns: 'auto',
  gridAutoFlow: 'row',
  gridAutoRows: 'auto',
  gridColumn: 'auto / auto',
  gridColumnEnd: 'auto',
  gridColumnGap: 'normal',
  gridColumnStart: 'auto',
  gridGap: 'normal normal',
  gridRow: 'auto / auto',
  gridRowEnd: 'auto',
  gridRowGap: 'normal',
  gridRowStart: 'auto',
  gridTemplate: 'none / none / none',
  gridTemplateAreas: 'none',
  gridTemplateColumns: 'none',
  gridTemplateRows: 'none',
  height: '100%',
  hyphenateCharacter: 'auto',
  hyphenateLimitChars: 'auto',
  hyphens: 'manual',
  imageOrientation: 'from-image',
  imageRendering: 'auto',
  inherits: '',
  initialLetter: 'normal',
  initialValue: '',
  inlineSize: '484',
  inset: 'auto',
  insetBlock: 'auto',
  insetBlockEnd: 'auto',
  insetBlockStart: 'auto',
  insetInline: 'auto',
  insetInlineEnd: 'auto',
  insetInlineStart: 'auto',
  isolation: 'auto',
  justifyContent: 'normal',
  justifyItems: 'normal',
  justifySelf: 'auto',
  left: 'auto',
  letterSpacing: 'normal',
  lightingColor: 'rgb(255, 255, 255)',
  lineBreak: 'auto',
  lineGapOverride: '',
  lineHeight: '35',
  listStyle: 'outside none disc',
  listStyleImage: 'none',
  listStylePosition: 'outside',
  listStyleType: 'disc',
  margin: '0',
  marginBlock: '0',
  marginBlockEnd: '0',
  marginBlockStart: '0',
  marginBottom: '0',
  marginInline: '0',
  marginInlineEnd: '0',
  marginInlineStart: '0',
  marginLeft: '0',
  marginRight: '0',
  marginTop: '0',
  marker: 'none',
  markerEnd: 'none',
  markerMid: 'none',
  markerStart: 'none',
  mask: 'none',
  maskType: 'luminance',
  mathDepth: '0',
  mathShift: 'normal',
  mathStyle: 'normal',
  maxBlockSize: 'none',
  maxHeight: 'none',
  maxInlineSize: 'none',
  maxWidth: 'none',
  minBlockSize: '0',
  minHeight: '0',
  minInlineSize: '0',
  minWidth: '0',
  mixBlendMode: 'normal',
  negative: '',
  objectFit: 'fill',
  objectPosition: '50% 50%',
  objectViewBox: 'none',
  offset: 'none 0 auto 0deg',
  offsetDistance: '0',
  offsetPath: 'none',
  offsetRotate: 'auto 0deg',
  opacity: '1',
  order: '0',
  orphans: '2',
  outline: 'rgb(255, 255, 255) none 0',
  outlineColor: 'rgb(255, 255, 255)',
  outlineOffset: '0',
  outlineStyle: 'none',
  outlineWidth: '0',
  overflow: 'visible',
  overflowAnchor: 'auto',
  overflowClipMargin: '0',
  overflowWrap: 'normal',
  overflowX: 'visible',
  overflowY: 'visible',
  overrideColors: '',
  overscrollBehavior: 'auto',
  overscrollBehaviorBlock: 'auto',
  overscrollBehaviorInline: 'auto',
  overscrollBehaviorX: 'auto',
  overscrollBehaviorY: 'auto',
  pad: '',
  padding: '0',
  paddingBlock: '0',
  paddingBlockEnd: '0',
  paddingBlockStart: '0',
  paddingBottom: '0',
  paddingInline: '0',
  paddingInlineEnd: '0',
  paddingInlineStart: '0',
  paddingLeft: '0',
  paddingRight: '0',
  paddingTop: '0',
  page: 'auto',
  pageBreakAfter: 'auto',
  pageBreakBefore: 'auto',
  pageBreakInside: 'auto',
  pageOrientation: '',
  paintOrder: 'normal',
  perspective: 'none',
  perspectiveOrigin: '242 4033.36',
  placeContent: 'normal',
  placeItems: 'normal',
  placeSelf: 'auto',
  pointerEvents: 'auto',
  position: 'static',
  prefix: '',
  quotes: 'auto',
  r: '0',
  range: '',
  resize: 'none',
  right: 'auto',
  rotate: 'none',
  rowGap: 'normal',
  rubyPosition: 'over',
  rx: 'auto',
  ry: 'auto',
  scale: 'none',
  scrollBehavior: 'auto',
  scrollMargin: '0',
  scrollMarginBlock: '0',
  scrollMarginBlockEnd: '0',
  scrollMarginBlockStart: '0',
  scrollMarginBottom: '0',
  scrollMarginInline: '0',
  scrollMarginInlineEnd: '0',
  scrollMarginInlineStart: '0',
  scrollMarginLeft: '0',
  scrollMarginRight: '0',
  scrollMarginTop: '0',
  scrollPadding: 'auto',
  scrollPaddingBlock: 'auto',
  scrollPaddingBlockEnd: 'auto',
  scrollPaddingBlockStart: 'auto',
  scrollPaddingBottom: 'auto',
  scrollPaddingInline: 'auto',
  scrollPaddingInlineEnd: 'auto',
  scrollPaddingInlineStart: 'auto',
  scrollPaddingLeft: 'auto',
  scrollPaddingRight: 'auto',
  scrollPaddingTop: 'auto',
  scrollSnapAlign: 'none',
  scrollSnapStop: 'normal',
  scrollSnapType: 'none',
  scrollbarGutter: 'auto',
  shapeImageThreshold: '0',
  shapeMargin: '0',
  shapeOutside: 'none',
  shapeRendering: 'auto',
  size: '',
  sizeAdjust: '',
  speak: 'normal',
  speakAs: '',
  src: '',
  stopColor: 'rgb(0, 0, 0)',
  stopOpacity: '1',
  stroke: 'none',
  strokeDasharray: 'none',
  strokeDashoffset: '0',
  strokeLinecap: 'butt',
  strokeLinejoin: 'miter',
  strokeMiterlimit: '4',
  strokeOpacity: '1',
  strokeWidth: '1',
  suffix: '',
  symbols: '',
  syntax: '',
  system: '',
  tabSize: '8',
  tableLayout: 'auto',
  textAlign: 'start',
  textAlignLast: 'auto',
  textAnchor: 'start',
  textCombineUpright: 'none',
  textDecoration: 'none solid rgb(255, 255, 255)',
  textDecorationColor: 'rgb(255, 255, 255)',
  textDecorationLine: 'none',
  textDecorationSkipInk: 'auto',
  textDecorationStyle: 'solid',
  textDecorationThickness: 'auto',
  textEmphasis: 'none rgb(255, 255, 255)',
  textEmphasisColor: 'rgb(255, 255, 255)',
  textEmphasisPosition: 'over',
  textEmphasisStyle: 'none',
  textIndent: '0',
  textOrientation: 'mixed',
  textOverflow: 'clip',
  textRendering: 'optimizespeed',
  textShadow: 'none',
  textSizeAdjust: 'auto',
  textTransform: 'none',
  textUnderlineOffset: 'auto',
  textUnderlinePosition: 'auto',
  top: 'auto',
  touchAction: 'auto',
  transform: 'none',
  transformBox: 'view-box',
  transformOrigin: '242 4033.36',
  transformStyle: 'flat',
  transition: 'all 0s ease 0s',
  transitionDelay: '0s',
  transitionDuration: '0s',
  transitionProperty: 'all',
  transitionTimingFunction: 'ease',
  translate: 'none',
  unicodeBidi: 'normal',
  unicodeRange: '',
  userSelect: 'auto',
  vectorEffect: 'none',
  verticalAlign: 'baseline',
  viewTransitionName: 'none',
  visibility: 'visible',
  whiteSpace: 'normal',
  widows: '2',
  width: '100%',
  willChange: 'auto',
  wordBreak: 'normal',
  wordSpacing: '0',
  wordWrap: 'normal',
  writingMode: 'horizontal-tb',
  x: '0',
  y: '0',
  zIndex: 'auto',
  zoom: '1',
  cssFloat: 'none',
  cssText: '',
  length: 351,
  parentRule: null
}

export const DEFAULT_VIEW_STYLES = {
  display: 'block'
}
export const DEFAULT_TEXT_STYLES = {
  display: 'inline'
}

export const DEFAULT_PARA_STYLES = {
  display: 'block',
  marginBottom: 20,
  fontSize: 16,
  lineHeight: 23
}

export const DEFAULT_STRONG_STYLES = {
  display: 'inline',
  fontWeight: 700
}

export const DEFAULT_IMG_STYLES = {
  display: 'inline',
  width: 16,
  height: 16
}

export const EXTEND_STYLE_KEYS = [
  'alignItems',
  'color',
  'fontFamily',
  'fontSize',
  'fontWeight',
  'letterSpacing',
  'lineHeight',
  'textAlign',
  'visivility',
  'wordSpacing'
]
